FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Set environment variables
ENV SUPABASE_URL=${SUPABASE_URL}
ENV SUPABASE_KEY=${SUPABASE_KEY}
ENV SUPABASE_EMAIL=${SUPABASE_EMAIL}
ENV SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
ENV SHEET_URLS=${SHEET_URLS}
ENV TABLE_NAME=${TABLE_NAME}

EXPOSE 8000

CMD ["opentelemetry-instrument", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 